/**
 * Lightning Network Configuration Module
 *
 * This module configures connections to LND (Lightning Network Daemon) nodes.
 * We'll be connecting to two separate nodes:
 * - Node A (Receiver): Generates invoices to receive payments
 * - Node B (Sender): Sends payments to invoices
 *
 * LND Communication:
 * LND exposes a gRPC API for programmatic interaction. To connect, we need:
 * 1. TLS Certificate: Ensures encrypted communication with the node
 * 2. Macaroon: Authentication token with specific permissions (like an API key)
 * 3. Host Address: The node's network location (host:port)
 *
 * In Polar (our local Lightning Network environment):
 * - Each node runs on a different port (e.g., 10001, 10002, 10003)
 * - Polar generates TLS certs and macaroons automatically
 * - You can find these files in Polar's data directory
 */

import fs from 'fs';
import dotenv from 'dotenv';

// Load environment variables
dotenv.config();

/**
 * Lightning Node Configuration Interface
 *
 * Defines the structure for LND node connection details.
 */
export interface LightningNodeConfig {
  host: string; // Node's network address (e.g., "localhost:10001")
  cert: Buffer; // TLS certificate for secure communication
  macaroon: Buffer; // Authentication credential
}

/**
 * Read File Helper
 *
 * Safely reads a file and returns its contents as a Buffer.
 * Throws descriptive errors if the file doesn't exist or can't be read.
 *
 * @param filePath - Absolute path to the file
 * @param fileType - Description of file type (for error messages)
 * @returns File contents as Buffer
 */
const readFile = (filePath: string, fileType: string): Buffer => {
  try {
    // Check if file exists
    if (!fs.existsSync(filePath)) {
      throw new Error(`${fileType} file not found at: ${filePath}`);
    }

    // Read file contents
    const content = fs.readFileSync(filePath);

    console.log(`✅ Successfully loaded ${fileType} from ${filePath}`);
    return content;
  } catch (error) {
    console.error(`❌ Error reading ${fileType} file:`, error);
    throw new Error(
      `Failed to read ${fileType}. Please check your .env configuration and ensure the file exists at: ${filePath}`
    );
  }
};

/**
 * Node A Configuration (Receiver Node)
 *
 * This node will be used to generate invoices and receive payments.
 */
export const getNodeAConfig = (): LightningNodeConfig => {
  const host = process.env.LND_A_HOST || 'localhost:10001';
  const certPath = process.env.LND_A_CERT_PATH;
  const macaroonPath = process.env.LND_A_MACAROON_PATH;

  // Validate required environment variables
  if (!certPath || !macaroonPath) {
    throw new Error(
      'Missing Node A configuration. Please set LND_A_CERT_PATH and LND_A_MACAROON_PATH in your .env file.\n' +
        'You can find these files in Polar after creating your network.\n' +
        'Example paths:\n' +
        '  LND_A_CERT_PATH=/Users/YourName/.polar/networks/1/volumes/lnd/alice/tls.cert\n' +
        '  LND_A_MACAROON_PATH=/Users/YourName/.polar/networks/1/volumes/lnd/alice/data/chain/bitcoin/regtest/admin.macaroon'
    );
  }

  return {
    host,
    cert: readFile(certPath, 'Node A TLS certificate'),
    macaroon: readFile(macaroonPath, 'Node A macaroon'),
  };
};

/**
 * Node B Configuration (Sender Node)
 *
 * This node will be used to pay invoices generated by Node A.
 *
 */
export const getNodeBConfig = (): LightningNodeConfig => {
  const host = process.env.LND_B_HOST || 'localhost:10002';
  const certPath = process.env.LND_B_CERT_PATH;
  const macaroonPath = process.env.LND_B_MACAROON_PATH;

  // Validate required environment variables
  if (!certPath || !macaroonPath) {
    throw new Error(
      'Missing Node B configuration. Please set LND_B_CERT_PATH and LND_B_MACAROON_PATH in your .env file.\n' +
        'You can find these files in Polar after creating your network.\n' +
        'Example paths:\n' +
        '  LND_B_CERT_PATH=/Users/YourName/.polar/networks/1/volumes/lnd/bob/tls.cert\n' +
        '  LND_B_MACAROON_PATH=/Users/YourName/.polar/networks/1/volumes/lnd/bob/data/chain/bitcoin/regtest/admin.macaroon'
    );
  }

  return {
    host,
    cert: readFile(certPath, 'Node B TLS certificate'),
    macaroon: readFile(macaroonPath, 'Node B macaroon'),
  };
};

/**
 * Validate Lightning Configuration
 *
 * Checks that all required configuration is present before starting the server.
 * This prevents runtime errors when trying to connect to nodes.
 *
 * @returns true if configuration is valid
 * @throws Error if configuration is missing or invalid
 */
export const validateLightningConfig = (): boolean => {
  try {
    console.log('\n🔍 Validating Lightning Network configuration...\n');

    // Try to load both node configurations
    const nodeA = getNodeAConfig();
    console.log(`✅ Node A configured at ${nodeA.host}`);

    const nodeB = getNodeBConfig();
    console.log(`✅ Node B configured at ${nodeB.host}`);

    console.log('\n✅ Lightning Network configuration is valid!\n');
    return true;
  } catch (error) {
    console.error('\n❌ Lightning Network configuration error:\n');
    if (error instanceof Error) {
      console.error(error.message);
    }
    console.error(
      '\n💡 Tip: Make sure you have:\n' +
        '  1. Created a network in Polar\n' +
        '  2. Added at least 2 LND nodes\n' +
        '  3. Started the network\n' +
        '  4. Copied the correct file paths to your .env file\n'
    );
    throw error;
  }
};
